# Generated by Django 6.0 on 2025-12-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='author_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.category'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
